In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
insurance = pd.read_csv("data/insurance_medical_cost.csv")

In [5]:
insurance.head()

   age     sex    bmi  children smoker     region   charges
0   56  female  27.02         2     no  northwest  23156.27
1   46    male  29.40         1     no  southwest  19456.82
2   32  female  25.97         5     no  northwest  20395.06
3   60  female  30.80         1     no  northwest  26350.83
4   25  female  26.81         0     no  southwest  13844.33

In [6]:
insurance.shape

(1338, 7)

In [7]:
insurance.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='str')

In [8]:
insurance.info

<bound method DataFrame.info of       age     sex    bmi  children smoker     region   charges
0      56  female  27.02         2     no  northwest  23156.27
1      46    male  29.40         1     no  southwest  19456.82
2      32  female  25.97         5     no  northwest  20395.06
3      60  female  30.80         1     no  northwest  26350.83
4      25  female  26.81         0     no  southwest  13844.33
...   ...     ...    ...       ...    ...        ...       ...
1333   60  female  30.87         2     no  northwest  23521.39
1334   63    male  31.77         3    yes  northwest  61074.14
1335   21  female  27.19         0     no  southeast  14774.56
1336   43  female  29.42         3     no  northwest  21596.07
1337   46    male  26.55         0     no  northeast  18149.82

[1338 rows x 7 columns]>

In [9]:
insurance.duplicated().sum()

np.int64(0)

In [10]:
insurance.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [11]:
insurance.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     41.036622    30.448475     1.092676  26947.834066
std      13.528861     5.966884     1.228710  12996.479469
min      18.000000    15.960000     0.000000   8783.150000
25%      29.000000    26.332500     0.000000  18667.667500
50%      42.000000    30.620000     1.000000  22391.445000
75%      52.000000    34.510000     2.000000  27196.797500
max      64.000000    47.260000     5.000000  63770.430000